#!/bin/bash
#Quand tu formattes, tu réinstalles tout ça ;)
#apt-get -y
sudo apt-get -y update

echo "software essential"
sudo apt-get -y install software-properties-common python-software-properties

echo "Installing cmake essential"
sudo apt-get -y install build-essential cmake

echo "Installing vim-gnome (xclipboard)"
sudo apt-get -y install vim-gnome

echo "Installing Python PIP"
sudo apt-get -y install python-pip
sudo apt-get -y install python-dev

echo "Installing Kolour"
sudo apt-get -y install kolourpaint4

echo "Installing ssh"
sudo apt-get -y install ssh

echo "Installing curl"
sudo apt-get -y install curl

echo "Installing sublime 3"
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-get -y update
sudo apt-get -y install sublime-text-installer

echo "Install tmux"
sudo apt-get -y install tmux

# echo "Install nodejs"
# fix this
# curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
# sudo apt-get install -y nodejs

echo "Installing ruby"
sudo apt-get install -y rubygems-integration

echo "Installing SaSS"
sudo su -c "gem install sass"

echo "Install Shutter"
sudo add-apt-repository -y ppa:shutter/ppa
sudo apt-get update -y
sudo apt-get install -y shutter

echo "NPM installation"
sudo npm install -g eslint
sudo npm install -g babel-eslint
sudo npm install -g eslint-plugin-react
